server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lingframe;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  cache:
    type: simple

lingframe:
  enabled: true
  dev-mode: true
  preload-api-jars:
    - ../lingframe-example-order-api
    - lingframe-examples/lingframe-example-order-api
  ling-home: lings
  ling-roots:
    - ../lingframe-example-ling-order
    - ../lingframe-example-ling-user
    - ../lingframe-example-ling-user-canary
    - lingframe-examples/lingframe-example-ling-order
    - lingframe-examples/lingframe-example-ling-user
    - lingframe-examples/lingframe-example-ling-user-canary
  ling-core-governance:
    enabled: false
    govern-internal-calls: true
    check-permissions: true
  dashboard:
    enabled: true
    install-enabled: true

springdoc:
  cache:
    disabled: true
  packages-to-scan: com.lingframe
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

logging:
  level:
    com.lingframe: DEBUG
