user-ling: !!com.lingframe.api.config.GovernancePolicy
  audits: [
    ]
  capabilities:
  - accessType: EXECUTE
    capability: Ling_ENABLE
  - accessType: WRITE
    capability: cache:local
  - accessType: WRITE
    capability: storage:sql
  collaborationMode: PASSIVE
  invocation:
    cpuBudgetMsPerMinute: null
    fallbackValue: null
    maxConcurrentThreads: 1
    memoryBudgetMb: null
    rateLimitPerSecond: 1
    retryCount: null
    timeoutMs: 3000
  permissions: [
    ]
order-ling: !!com.lingframe.api.config.GovernancePolicy
  audits: [
    ]
  capabilities:
  - accessType: EXECUTE
    capability: Ling_ENABLE
  - accessType: WRITE
    capability: cache:local
  - accessType: WRITE
    capability: storage:sql
  collaborationMode: PASSIVE
  invocation:
    cpuBudgetMsPerMinute: null
    fallbackValue: null
    maxConcurrentThreads: null
    memoryBudgetMb: null
    rateLimitPerSecond: null
    retryCount: null
    timeoutMs: null
  permissions: [
    ]
