user-ling: !!com.lingframe.api.config.GovernancePolicy
  audits: [
    ]
  capabilities:
  - accessType: EXECUTE
    capability: Ling_ENABLE
  - accessType: EXECUTE
    capability: LING_ENABLE
  - accessType: READ
    capability: cache:local
  - accessType: EXECUTE
    capability: ipc:user-ling
  - accessType: EXECUTE
    capability: ipc:ling-stress-web
  - accessType: EXECUTE
    capability: ipc:order-ling
  - accessType: READ
    capability: storage:sql
  invocation:
    cpuBudgetMsPerMinute: null
    fallbackValue: null
    maxConcurrentThreads: 1
    memoryBudgetMb: null
    rateLimitPerSecond: 1
    retryCount: null
    timeoutMs: 3000
  permissions: [
    ]
  references: [
    ]
order-ling: !!com.lingframe.api.config.GovernancePolicy
  audits: [
    ]
  capabilities:
  - accessType: EXECUTE
    capability: Ling_ENABLE
  - accessType: EXECUTE
    capability: LING_ENABLE
  - accessType: WRITE
    capability: cache:local
  - accessType: EXECUTE
    capability: ipc:user-ling
  - accessType: EXECUTE
    capability: ipc:order-ling
  - accessType: WRITE
    capability: storage:sql
  invocation:
    cpuBudgetMsPerMinute: 500
    fallbackValue: null
    maxConcurrentThreads: 5
    memoryBudgetMb: 128
    rateLimitPerSecond: 10
    retryCount: 0
    timeoutMs: 1000
  permissions: [
    ]
  references: [
    ]
