<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lingframe</groupId>
        <artifactId>lingframe-example-saas-mall</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>lingframe-example-saas-ling-oauth</artifactId>
    <packaging>jar</packaging>

    <name>LingFrame :: Example :: SaaS Mall OAuth Ling</name>
    <description>SaaS商城三方社交登录灵元</description>

    <dependencies>
        <!-- 核心 API 契约 -->
        <dependency>
            <groupId>com.lingframe</groupId>
            <artifactId>lingframe-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 本项目公共契约 -->
        <dependency>
            <groupId>com.lingframe</groupId>
            <artifactId>lingframe-example-saas-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.16</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Ling-Id>saas-oauth-ling</Ling-Id>
                            <Ling-Version>${project.version}</Ling-Version>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
