<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.lingframe</groupId>
        <artifactId>lingframe-runtime</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>lingframe-native</artifactId>
    <packaging>jar</packaging>

    <name>LingFrame :: Native</name>
    <description>纯 Java 运行时</description>

    <dependencies>
        <dependency>
            <groupId>cn.lingframe</groupId>
            <artifactId>lingframe-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>check</id>
                        <goals><goal>check</goal></goals>
                        <configuration><skip>true</skip></configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
